/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.grocerystorepos.gui;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author ADMIN
 */
public class Homepage1 extends javax.swing.JPanel {

    private CardLayout cardLayout;  
     private JPanel cardPanel;  
    public Homepage1() {
        initComponents();
          // Khởi tạo CardLayout
        cardLayout = new CardLayout();
        jppro = new JPanel(cardLayout);  // Sử dụng jppro làm nơi chứa các trang

        // Tạo các panel cho các trang khác nhau
        JPanel homePanel = createHomePanel();
        JPanel designPanel = createDesignPanel();
        JPanel statsPanel = createStatisticsPanel();

        // Thêm các panel vào jppro
        jppro.add(homePanel, "Home");
        jppro.add(designPanel, "Design");
        jppro.add(statsPanel, "Statistics");

        // Thêm jppro vào Homepage1
        setLayout(new BorderLayout());
        setLayout(new BorderLayout());
        add(jppro, BorderLayout.CENTER);  // Thêm jppro vào JFrame chính
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        btndesign = new javax.swing.JButton();
        btnthongke = new javax.swing.JButton();
        jppro = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Quản Lý Cửa Hàng");

        btnhome.setText("Home");

        btndesign.setText("Trang design");
        btndesign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndesignActionPerformed(evt);
            }
        });

        btnthongke.setText("Trang Thống kê");

        jppro.setBackground(new java.awt.Color(255, 0, 51));
        jppro.setForeground(new java.awt.Color(255, 51, 102));

        javax.swing.GroupLayout jpproLayout = new javax.swing.GroupLayout(jppro);
        jppro.setLayout(jpproLayout);
        jpproLayout.setHorizontalGroup(
            jpproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        jpproLayout.setVerticalGroup(
            jpproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jppro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnhome)
                        .addGap(30, 30, 30)
                        .addComponent(btndesign)
                        .addGap(30, 30, 30)
                        .addComponent(btnthongke))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhome)
                    .addComponent(btndesign)
                    .addComponent(btnthongke))
                .addGap(71, 71, 71)
                .addComponent(jppro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndesignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndesignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndesignActionPerformed
 // Tạo trang chủ
    private JPanel createHomePanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());

        // Các nút điều hướng
        JPanel buttonPanel = new JPanel();
        JButton homeButton = new JButton("Home");
        JButton designButton = new JButton("Trang design");
        JButton statsButton = new JButton("Trang Thống kê");

        // Cài đặt hành động cho các nút
        homeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cardLayout.show(jppro, "Home");
            }
        });

        designButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cardLayout.show(jppro, "Design");
            }
        });

        statsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cardLayout.show(jppro, "Statistics");
            }
        });

        buttonPanel.add(homeButton);
        buttonPanel.add(designButton);
        buttonPanel.add(statsButton);

        // Thêm panel button vào phần dưới
        panel.add(buttonPanel, BorderLayout.SOUTH);
        return panel;
    }

    // Tạo trang Design
    private JPanel createDesignPanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        JLabel label = new JLabel("Trang Design", SwingConstants.CENTER);
        panel.add(label, BorderLayout.CENTER);

        // Nút quay lại
        JButton backButton = new JButton("Quay lại");
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cardLayout.show(jppro, "Home");
            }
        });
        panel.add(backButton, BorderLayout.SOUTH);

        return panel;
    }

    // Tạo trang Thống kê
    private JPanel createStatisticsPanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        JLabel label = new JLabel("Trang Thống kê", SwingConstants.CENTER);
        panel.add(label, BorderLayout.CENTER);

        // Nút quay lại
        JButton backButton = new JButton("Quay lại");
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cardLayout.show(jppro, "Home");
            }
        });
        panel.add(backButton, BorderLayout.SOUTH);

        return panel;
    }

    // Main method để chạy ứng dụng
    public static void main(String[] args) {
        JFrame frame = new JFrame("Homepage1");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(800, 600);
        frame.add(new Homepage1()); // Thêm Homepage1 vào JFrame
        frame.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndesign;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnthongke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jppro;
    // End of variables declaration//GEN-END:variables
}
